openapi: 3.0.1
info:
  description: "TestRestUsers REST API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  title: "TestRestUsers"
  version: v1.0
paths:
  "/add-user":
    post:
      operationId: addUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUser"
          application/xml:
            schema:
              $ref: "#/components/schemas/NewUser"
      responses:
        200:
          description: "User added successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserObject"
            application/xml:
              schema:
                $ref: "#/components/schemas/UserObject"
      tags: ["User"]
components:
  schemas:
    NewUser:
      type: object
      properties:
        screenName:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        password1:
          type: string
        password2:
          type: string
        role:
          type: string
    UserObject:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        screenName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        statusCode:
          type: integer
        statusMessage:
          type: string