/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package chat.service.model.impl;

import chat.service.model.ChatMessage;
import chat.service.model.ChatMessageModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ChatMessage service. Represents a row in the &quot;ticket_ChatMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ChatMessageModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChatMessageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChatMessageImpl
 * @generated
 */
@JSON(strict = true)
public class ChatMessageModelImpl
	extends BaseModelImpl<ChatMessage> implements ChatMessageModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a chat message model instance should use the <code>ChatMessage</code> interface instead.
	 */
	public static final String TABLE_NAME = "ticket_ChatMessage";

	public static final Object[][] TABLE_COLUMNS = {
		{"messageId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"ticketId", Types.BIGINT}, {"message", Types.VARCHAR},
		{"timestamp", Types.TIMESTAMP}, {"imageattached", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("messageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ticketId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("message", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("timestamp", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("imageattached", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ticket_ChatMessage (messageId LONG not null primary key,userId LONG,ticketId LONG,message VARCHAR(75) null,timestamp DATE null,imageattached TEXT null)";

	public static final String TABLE_SQL_DROP = "drop table ticket_ChatMessage";

	public static final String ORDER_BY_JPQL =
		" ORDER BY chatMessage.messageId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ticket_ChatMessage.messageId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TICKETID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long MESSAGEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ChatMessageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _messageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMessageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _messageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ChatMessage.class;
	}

	@Override
	public String getModelClassName() {
		return ChatMessage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ChatMessage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ChatMessage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChatMessage, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ChatMessage)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ChatMessage, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ChatMessage, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ChatMessage)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ChatMessage, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ChatMessage, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ChatMessage, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ChatMessage, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ChatMessage, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ChatMessage, Object>>();
		Map<String, BiConsumer<ChatMessage, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ChatMessage, ?>>();

		attributeGetterFunctions.put("messageId", ChatMessage::getMessageId);
		attributeSetterBiConsumers.put(
			"messageId",
			(BiConsumer<ChatMessage, Long>)ChatMessage::setMessageId);
		attributeGetterFunctions.put("userId", ChatMessage::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<ChatMessage, Long>)ChatMessage::setUserId);
		attributeGetterFunctions.put("ticketId", ChatMessage::getTicketId);
		attributeSetterBiConsumers.put(
			"ticketId",
			(BiConsumer<ChatMessage, Long>)ChatMessage::setTicketId);
		attributeGetterFunctions.put("message", ChatMessage::getMessage);
		attributeSetterBiConsumers.put(
			"message",
			(BiConsumer<ChatMessage, String>)ChatMessage::setMessage);
		attributeGetterFunctions.put("timestamp", ChatMessage::getTimestamp);
		attributeSetterBiConsumers.put(
			"timestamp",
			(BiConsumer<ChatMessage, Date>)ChatMessage::setTimestamp);
		attributeGetterFunctions.put(
			"imageattached", ChatMessage::getImageattached);
		attributeSetterBiConsumers.put(
			"imageattached",
			(BiConsumer<ChatMessage, String>)ChatMessage::setImageattached);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMessageId() {
		return _messageId;
	}

	@Override
	public void setMessageId(long messageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_messageId = messageId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public long getTicketId() {
		return _ticketId;
	}

	@Override
	public void setTicketId(long ticketId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ticketId = ticketId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTicketId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("ticketId"));
	}

	@JSON
	@Override
	public String getMessage() {
		if (_message == null) {
			return "";
		}
		else {
			return _message;
		}
	}

	@Override
	public void setMessage(String message) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_message = message;
	}

	@JSON
	@Override
	public Date getTimestamp() {
		return _timestamp;
	}

	@Override
	public void setTimestamp(Date timestamp) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_timestamp = timestamp;
	}

	@JSON
	@Override
	public String getImageattached() {
		if (_imageattached == null) {
			return "";
		}
		else {
			return _imageattached;
		}
	}

	@Override
	public void setImageattached(String imageattached) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imageattached = imageattached;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ChatMessage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ChatMessage toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ChatMessage>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChatMessageImpl chatMessageImpl = new ChatMessageImpl();

		chatMessageImpl.setMessageId(getMessageId());
		chatMessageImpl.setUserId(getUserId());
		chatMessageImpl.setTicketId(getTicketId());
		chatMessageImpl.setMessage(getMessage());
		chatMessageImpl.setTimestamp(getTimestamp());
		chatMessageImpl.setImageattached(getImageattached());

		chatMessageImpl.resetOriginalValues();

		return chatMessageImpl;
	}

	@Override
	public ChatMessage cloneWithOriginalValues() {
		ChatMessageImpl chatMessageImpl = new ChatMessageImpl();

		chatMessageImpl.setMessageId(
			this.<Long>getColumnOriginalValue("messageId"));
		chatMessageImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		chatMessageImpl.setTicketId(
			this.<Long>getColumnOriginalValue("ticketId"));
		chatMessageImpl.setMessage(
			this.<String>getColumnOriginalValue("message"));
		chatMessageImpl.setTimestamp(
			this.<Date>getColumnOriginalValue("timestamp"));
		chatMessageImpl.setImageattached(
			this.<String>getColumnOriginalValue("imageattached"));

		return chatMessageImpl;
	}

	@Override
	public int compareTo(ChatMessage chatMessage) {
		long primaryKey = chatMessage.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ChatMessage)) {
			return false;
		}

		ChatMessage chatMessage = (ChatMessage)object;

		long primaryKey = chatMessage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ChatMessage> toCacheModel() {
		ChatMessageCacheModel chatMessageCacheModel =
			new ChatMessageCacheModel();

		chatMessageCacheModel.messageId = getMessageId();

		chatMessageCacheModel.userId = getUserId();

		chatMessageCacheModel.ticketId = getTicketId();

		chatMessageCacheModel.message = getMessage();

		String message = chatMessageCacheModel.message;

		if ((message != null) && (message.length() == 0)) {
			chatMessageCacheModel.message = null;
		}

		Date timestamp = getTimestamp();

		if (timestamp != null) {
			chatMessageCacheModel.timestamp = timestamp.getTime();
		}
		else {
			chatMessageCacheModel.timestamp = Long.MIN_VALUE;
		}

		chatMessageCacheModel.imageattached = getImageattached();

		String imageattached = chatMessageCacheModel.imageattached;

		if ((imageattached != null) && (imageattached.length() == 0)) {
			chatMessageCacheModel.imageattached = null;
		}

		return chatMessageCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ChatMessage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ChatMessage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChatMessage, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ChatMessage)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ChatMessage>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ChatMessage.class, ModelWrapper.class);

	}

	private long _messageId;
	private long _userId;
	private long _ticketId;
	private String _message;
	private Date _timestamp;
	private String _imageattached;

	public <T> T getColumnValue(String columnName) {
		Function<ChatMessage, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ChatMessage)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("messageId", _messageId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("ticketId", _ticketId);
		_columnOriginalValues.put("message", _message);
		_columnOriginalValues.put("timestamp", _timestamp);
		_columnOriginalValues.put("imageattached", _imageattached);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("messageId", 1L);

		columnBitmasks.put("userId", 2L);

		columnBitmasks.put("ticketId", 4L);

		columnBitmasks.put("message", 8L);

		columnBitmasks.put("timestamp", 16L);

		columnBitmasks.put("imageattached", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ChatMessage _escapedModel;

}