/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package chat.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ChatMessage service. Represents a row in the &quot;ticket_ChatMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>chat.service.model.impl.ChatMessageModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>chat.service.model.impl.ChatMessageImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChatMessage
 * @generated
 */
@ProviderType
public interface ChatMessageModel extends BaseModel<ChatMessage> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chat message model instance should use the {@link ChatMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this chat message.
	 *
	 * @return the primary key of this chat message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chat message.
	 *
	 * @param primaryKey the primary key of this chat message
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the message ID of this chat message.
	 *
	 * @return the message ID of this chat message
	 */
	public long getMessageId();

	/**
	 * Sets the message ID of this chat message.
	 *
	 * @param messageId the message ID of this chat message
	 */
	public void setMessageId(long messageId);

	/**
	 * Returns the user ID of this chat message.
	 *
	 * @return the user ID of this chat message
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this chat message.
	 *
	 * @param userId the user ID of this chat message
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this chat message.
	 *
	 * @return the user uuid of this chat message
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this chat message.
	 *
	 * @param userUuid the user uuid of this chat message
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the ticket ID of this chat message.
	 *
	 * @return the ticket ID of this chat message
	 */
	public long getTicketId();

	/**
	 * Sets the ticket ID of this chat message.
	 *
	 * @param ticketId the ticket ID of this chat message
	 */
	public void setTicketId(long ticketId);

	/**
	 * Returns the message of this chat message.
	 *
	 * @return the message of this chat message
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this chat message.
	 *
	 * @param message the message of this chat message
	 */
	public void setMessage(String message);

	/**
	 * Returns the timestamp of this chat message.
	 *
	 * @return the timestamp of this chat message
	 */
	public Date getTimestamp();

	/**
	 * Sets the timestamp of this chat message.
	 *
	 * @param timestamp the timestamp of this chat message
	 */
	public void setTimestamp(Date timestamp);

	/**
	 * Returns the imageattached of this chat message.
	 *
	 * @return the imageattached of this chat message
	 */
	@AutoEscape
	public String getImageattached();

	/**
	 * Sets the imageattached of this chat message.
	 *
	 * @param imageattached the imageattached of this chat message
	 */
	public void setImageattached(String imageattached);

	@Override
	public ChatMessage cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}